// pages/_app.js
import { useEffect } from "react";
import { Inter } from "next/font/google";
import "./../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function App({ Component, pageProps }) {
  useEffect(() => {
    inter.load();
  }, []);

  return (
    <>
      <html lang="pt-BR">
        <body className={inter.className}>
          <Component {...pageProps} />
        </body>
      </html>
      {inter.getStyleElement()}
    </>
  );
}
